### ISSUE TITLE
Values don't hold

### ISSUE THREAD

**Issue by bridgestew** [Lynx3d/tinker_tools#2]
I don't know if this was intentional or not. I skimmed the changelog, but didn't see it in 1.2.4 notes.

When I enter a value to rotate a block (say, Yaw 90), if I change the checkbox from absolute to relative, the value disappears and I must re-enter it. This may not be the most critical thing, but it is a wee bit annoying.

Thanks!

**Comment by Lynx3d** [comment]
It is indeed intentional and also mentioned in the change log:
- Separate input values for absolute and relative modes.

That means, absolute and relative mode have their own input values and will not overwrite each other. Main reason is that for move and scale, they have different ranges of valid values and accidently using values for one mode in the other can seriously mess up stuff.

Sure for rotation there are basically no invalid values, but I figured it's still nice nice  to keep two sets of values as you may re-use them in their respective mode independent of what you do in the other mode.

**Comment by bridgestew** [comment]
Ok, thanks for the explanation. Not sure how I missed it (or just misread it) in the release notes.
